### ISSUE TITLE
The google drive link doesn't work

### ISSUE THREAD

**Issue by mysterefrank** [danxuhk/ContinuousCRF-CNN#1]
I'm getting a 404 error

**Comment by eturner303** [comment]
So am I.  Are the models available anywhere else?

**Comment by glhfgg1024** [comment]
Hi, could you please also upload one copy onto BaiduYun? The google drive might not be available in China Mainland. The BaiduYun might be more suitable for sharing these data as it would be available across the whole world.

**Comment by mysterefrank** [comment]
It's not just china glhfgg, the link doesn't work in America. Google drive should be international.

**Comment by ctiennot** [comment]
Doesn't work indeed :/

**Comment by danxuhk** [comment]
Please try this link https://drive.google.com/drive/u/1/folders/0ByWGxNo3TouJRDFPdWF4UWFubVk
