### ISSUE TITLE
Stranger results from your provided prototxt and model

### ISSUE THREAD

**Issue by xiaofeng94** [danxuhk/ContinuousCRF-CNN#5]
I am appreciating your remarkable work and want to have a try.

I follow the steps in https://github.com/s9xie/hed/blob/master/examples/hed/HED-tutorial.ipynb to use CCRF_NYU.prototxt and CCRF_NYU.caffemodel provided by you, but get stranger results shown below.
![predict](https://user-images.githubusercontent.com/9328733/38143274-5182edbc-3472-11e8-9bbf-3ddefaf5d052.jpg)
![rgb](https://user-images.githubusercontent.com/9328733/38143276-55d8a2a8-3472-11e8-8d0b-606c2c20e965.jpg)

would you please tell me how to test with your model, thank you!

**Comment by elezchan** [comment]
i met the same problem, have you made a test succefully ?

**Comment by danxuhk** [comment]
Please use the testing script in examples/CCRF-CNN/nyud_test.py to test...
