### ISSUE TITLE
"caffe.LayerParameter" has no field named "multi_continuous_meanfield_param"

### ISSUE THREAD

**Issue by mibrahimy** [danxuhk/ContinuousCRF-CNN#7]
I am getting this error, although I am using your caffe. Am I doing some mistake?

**Comment by JamesDeng88** [comment]
I got the same error. The caffe version problem? any idea?

**Comment by mibrahimy** [comment]
Yes, 
Make the caffe version provided in the ContinuousCRF-CNN folder and the error will go away.
The error is suggesting it is linking with the default caffe which doesn't have "multi_continuous_meanfield_param"
