### ISSUE TITLE
Did you do some other processing on ground truth depth of NYU2? I got much worse accuracy than the value reported in the paper.

### ISSUE THREAD

**Issue by ghost** [danxuhk/ContinuousCRF-CNN#9]

**Comment by danxuhk** [comment]
what accuracy do you get?

**Comment by ghost** [comment]
I got abs_rel: 0.1818, rms: 0.6857, log10: 0.074, a1: 0.732, a2: 0.930, a3: 0.981. Did you do some preprocessing such as normalization on ground truth?

**Comment by danxuhk** [comment]
We didn't process the ground-truth data, but we saved the depth data into 16bit images for loading and we evaluated only in the valid range of [0.7, 10] for NYUD.
